# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MomsDayDaughter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MomsDayDaughter
pod 'MGStarRatingView', '~> 0.3.0'
pod 'DLRadioButton', '~> 1.4'
pod 'UITextView+Placeholder'
  target 'MomsDayDaughterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
