# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MomsDayDaughter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MomsDayDaughter
pod 'SwiftyStarRatingView'
pod 'DLRadioButton', '~> 1.4'
pod 'UITextView+Placeholder'
pod 'AlamofireImage', '~> 3.5'
pod 'AlamofireObjectMapper', '~> 5.2'
  target 'MomsDayDaughterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
